app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='sapphiremeetapp'
urlpatterns = [
path('',views.home,name='home'),
path('about/',views.about,name='about'),
path('channel/',views.channelq,name='channel'),
path('enter/',views.enter,name='enter'),
path('notfound/',views.notfound,name='notfound'),
path('auth/',views.auth,name='auth'),
path('hostpage/<slug:docid>',views.hostpage,name='hostpage'),
path('entering/',views.entering,name='entering'),
path('contactus/',views.contact,name='contactus'),
path('price/',views.pricing,name='price'),
path('googleauth/<slug:val>',views.authA,name='authgoogle'),
path('appleauth/',views.authB,name='authapple'),
path('applesignup/',views.authC,name='authapplesignup'),
path('chat/',views.commingsoon,name='chat'),
path('obs/',views.obs,name='OBS'),
path('history/',views.history,name='history'),
path('termsandcondition/',views.tac,name='tac'),
path('privacypolicy/',views.privacy,name='privacy'),
path('steps/',views.steps,name='steps'),

]

sapphiremeetweb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

class user(models.Model):
    id=models.AutoField
    name = models.TextField(max_length=300)
    email=models.TextField(max_length=300)
    passcode= models.TextField(max_length=300)
    def __str__(self):
        return str(self.id)

class msg(models.Model):
    id=models.AutoField
    name=models.TextField(max_length=300)
    email=models.TextField(max_length=300)
    msg=models.TextField(max_length=300)
    subject=models.TextField(max_length=300)
    def __str__(self):
        return str(self.id)

app/views.py
from django.shortcuts import render
from django import http
from . import models
def home(req):
    return render(req,'index-3.html')
def about(req):
    return http.HttpResponse('ok')
def contact(req):
    name=req.POST.get('name','')
    email=req.POST.get('email','')
    msg=req.POST.get('message','')
    subject=req.POST.get('subject','')
    arg={'val':False}
    if name!='' and email!='' and msg!='' and subject!='':
     val=models.msg()
     val.name=name
     val.email=email
     val.msg=msg
     val.subject=subject
     val.save()
     arg['val']=True

    return render(req,'contact.html',arg)
def pricing(req):
    return render(req,'pricing.html')
def channelq(req):
    print(req.POST.get('roomid'))
    return render(req,'channel.html',{'passcode':str(req.POST.get('passcode','')),"date":str(req.POST.get('date','random')),'topic':str(req.POST.get('top','random')),'roomid':str(req.POST.get('roomid','')),'name':str(req.POST.get('name',''))})
def enter(req):
    return render(req,'enter.html')
def notfound(req):
    return render(req,'notfound.html')
def auth(req):
    return render(req,'authpage.html')
def hostpage(req,docid):
    return render(req,'hostpage.html',{'docid':docid})
def authA(req,val):
    return render(req,'googleauth.html',{'val':val})
def entering(req):
    return render(req,'index.html')
def authB(req):
    email = req.POST.get('email','')
    password = req.POST.get('password','')
    arg={}
    if email!='' and password!='' and models.user.objects.filter(email=email,passcode=password):
        arg['auth']='true'
    else :
        arg['auth']='false'
        arg['comeback']='true'
    arg['email']=email

    return render(req,'appleauth.html',arg)
def authC(req):
    username=req.POST.get('username','')
    email = req.POST.get('email','')
    password = req.POST.get('pass','')
    arg={}
    if username!="" and email !='' and password!='' and not models.user.objects.filter(email=email,passcode=password):
        a=models.user()
        a.email=email
        a.name=username
        a.passcode=password
        a.save()
        arg['auth']=True
    elif email=='' and password=='' and username=='':
        arg['auth']='fs'

    else:
        arg['auth']=False

    return render(req,'applesignup.html',arg)
def commingsoon(req):
    return render(req,'chat.html')
def obs(req):
    return render(req,'index12.html')
def history(req):
    return render(req,'history.html')
def privacy(req):
    return render(req,'privacypolicy.html')
def tac(req):
    return render(req,'termandcondition.html')
def steps(req):
    return render(req,'steps.html')

app/templates/appleauth.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Apple Auth</title>
  </head>
<style>
    .mar{
        margin: 15%;
    }
    .coo{
        background-color:silver;
    }
    .marq{
        margin-left: 43%;
        margin-top: 40px;
    }
</style>
{% load static %}
  <body class="coo">
      <img class="marq" src="{% static 'apple.png' %}" alt="" width='100'>
    <form class="mar" method="POST" action='/appleauth/' id='fom'> {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name='email'>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name='password'>
  </div>

  <button type="button" id = 'logi' class="btn btn-primary">Login</button>
  <button type="button" id="newa" class="btn btn-secondary">Create Your Account</button>
</form>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-analytics.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-firestore.js"></script>
    <script>
       var firebaseConfig = {
      apiKey: "AIzaSyD459mLh3V-U83_cD2ZgM4herSAq76CAHY",
      authDomain: "sapphire-meet.firebaseapp.com",
      databaseURL: "https://sapphire-meet.firebaseio.com",
      projectId: "sapphire-meet",
      storageBucket: "sapphire-meet.appspot.com",
      messagingSenderId: "414973538233",
      appId: "1:414973538233:web:387f730b004839c2369068",
      measurementId: "G-7ZBSX6GSDT"
    };
    firebase.initializeApp(firebaseConfig);
    var val = '{{auth}}';
if( val=='true' )
{
  var kan = async ()=>{
var auth = firebase.auth();
  var email = '{{email}}'.split('.')[0];



    var firestore = firebase.firestore();
    var doc = firestore.doc('ios/79G4HWeB4dFm5Fr5EUk8');
    var data = await doc.get();
    if(data.data()[email]!=null)
    {
    sessionStorage.setItem('user',data.data()[email]);
    location.href='/hostpage/'+data.data()[email].split('/')[1];
    }
    else
    {
    alert('no user avalable');
        sessionStorage.setItem('visit','null');
    }



  }
  kan();

}
  console.log(val);
  if((val=='false')&&('{{comeback}}'=='true')&&(sessionStorage.getItem('visit')!='null')&&(sessionStorage.getItem('visit')!=null))
  {
       alert('Wrong Credentials');
        sessionStorage.setItem('visit','null');

  }
document.getElementById('logi').onclick=()=>{
    sessionStorage.setItem('visit','val');
    document.getElementById('fom').submit();


};
document.getElementById('newa').onclick=()=>{

    location.href='/applesignup';


};
    </script>
    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/applesignup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<style>
    .marg{
        margin: 10%;
    }
    .col{
        background-color: silver;
    }
</style>

<body class="col">
{% if auth == True %}
<div class="alert alert-success" role="alert">
  Created
</div>
{% elif auth == False %}
<div class="alert alert-danger" role="alert">
either users alredy or some other error
</div>


{% endif %}

    <form class="marg" method="POST" id='signup' action='/applesignup/'> {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Email</label>
            <input type="email" class="form-control" id="inputEmail4" name='email'>
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Password</label>
            <input type="password" class="form-control" id="inputPassword4" name='pass'>
          </div>
        </div>
          <div class="form-group col-md-6">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" placeholder="Enter the username" name='username'>
          </div>
        </div>
        </div>
        <button type = 'button' id='sign' class="btn btn-primary">Sign in</button>
      </form>
</body>
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-firestore.js"></script>
<script>
     var firebaseConfig = {
      apiKey: "AIzaSyD459mLh3V-U83_cD2ZgM4herSAq76CAHY",
      authDomain: "sapphire-meet.firebaseapp.com",
      databaseURL: "https://sapphire-meet.firebaseio.com",
      projectId: "sapphire-meet",
      storageBucket: "sapphire-meet.appspot.com",
      messagingSenderId: "414973538233",
      appId: "1:414973538233:web:387f730b004839c2369068",
      measurementId: "G-7ZBSX6GSDT"
    };
    firebase.initializeApp(firebaseConfig);
    document.getElementById('sign').onclick = async ()=>{
try{
   var email= document.getElementById('inputEmail4').value.split('.')[0];
var firestore = firebase.firestore();
var doc = firestore.doc('ios/79G4HWeB4dFm5Fr5EUk8');

var coll=firestore.collection('users');

console.log('ddone');

var ref= await coll.add({
    'name':document.getElementById('username').value,
    'account':'free',
    'roomid':[],

});

await doc.update({
    [email]: ref.path,
});
console.log('done');

document.getElementById('signup').submit();
}
catch(e)
{
    console.log(e);
}
    };
</script>
</html>

app/templates/chat.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com    @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    {% load static %}
    <title>Sapphire Meet Web</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"> {% load static %}
    <link rel="stylesheet" href="{% static 'chatpannel/css/chat.css' %}">
    <link rel="stylesheet" href="{% static 'chatpannel/css/pre.css' %}">
</head>

<body>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="container app">
        <div class="row app-one">
            <div class="col-sm-4 side">
                <div class="side-one">
                    <div class="row heading">
                        <div class="col-sm-3 col-xs-3 heading-avatar">
                            <div class="heading-avatar-icon" id="ownavtar">
                                <img src="https://bootdey.com/img/Content/avatar/avatar1.png">
                            </div>
                        </div>
                        <div class="col-sm-1 col-xs-1  heading-dot  pull-right">
                            <i class="fa fa-ellipsis-v fa-2x  pull-right" aria-hidden="true"></i>
                        </div>
                        <div class="col-sm-2 col-xs-2 heading-compose  pull-right">
                            <i class="fa fa-comments fa-2x  pull-right" aria-hidden="true"></i>
                        </div>
                    </div>

                    <div class="row searchBox">
                        <div class="col-sm-12 searchBox-inner">
                            <div class="form-group has-feedback">
                                <input id="searchText" type="text" class="form-control" name="searchText" placeholder="Search">
                                <span class="glyphicon glyphicon-search form-control-feedback"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row sideBar" id='chattile'>
                        <div class="row sideBar-body">
                            <div class="col-sm-3 col-xs-3 sideBar-avatar">
                                <div class="avatar-icon">
                                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png">
                                </div>
                            </div>
                            <div class="col-sm-9 col-xs-9 sideBar-main">
                                <div class="row">
                                    <div class="col-sm-8 col-xs-8 sideBar-name">
                                        <span class="name-meta">
                </span>
                                    </div>
                                    <div class="col-sm-4 col-xs-4 pull-right sideBar-time">
                                        <span class="time-meta pull-right">
                </span>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>

            <div class="col-sm-8 conversation">
                <div class="row heading">
                    <div class="col-sm-2 col-md-1 col-xs-3 heading-avatar">
                        <div class="heading-avatar-icon" id='avatar'>
                            <img src="">
                        </div>
                    </div>
                    <div class="col-sm-8 col-xs-7 heading-name">
                        <a class="heading-name-meta" id='headname'>
          </a>

                    </div>
                    <div class="col-sm-1 col-xs-1  heading-dot pull-right">
                        <i class="fa fa-ellipsis-v fa-2x  pull-right" aria-hidden="true"></i>
                    </div>
                </div>

                <div class="message" id="conversation">
                    <div class="message-previous">
                        <div class="col-sm-12 previous">
                            <a onclick="previous(this)" id="ankitjain28" name="20">

                            </a>
                        </div>
                    </div>
                    <div id='chatmess'>

                        <!-- Ends -->
                        <!-- 
                        <div class="content">
                            <div class="back-to-article">
                                <p>
                                    <a href="http://smallenvelop.com/blog/display-loading-icon-page-loads-completely/">
                                        << Back to the article !!</a>
                                </p>
                            </div>
                            <img src="http://smallenvelop.com/wp-content/uploads/2014/08/simple-pre-loader.jpg
" style="visibility: hidden; width:100%; height: auto;">
                        </div>
                        <style>
                            .content {
                                background: url(http://smallenvelop.com/wp-content/uploads/2014/08/simple-pre-loader.jpg
) center no-repeat;
                                background-size: 100%;
                                width: 100%;
                            }
                        </style> -->
                        <h2 class='preloader'> &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chat here</h2>
                        <div class="row message-body">
                            <div class="col-sm-12 message-main-receiver">
                                <!-- <div class="receiver">
                                    <div class="message-text">
                                        Hi, what are you doing?!
                                    </div>
                                    <span class="message-time pull-right">
                Sun
              </span>
                                </div> -->
                            </div>
                        </div>

                        <!-- <div class="row message-body">
                            <div class="col-sm-12 message-main-sender">
                                <div class="sender">
                                    <div class="message-text">
                                        I am doing nothing man!
                                    </div>
                                    <span class="message-time pull-right">
                Sun
              </span>
                                </div>
                            </div>
                        </div> -->
                    </div>
                </div>
                <div class="row reply">
                    <div class="col-sm-1 col-xs-1 reply-emojis">
                        <i class="fa fa-image fa-2x"></i>
                    </div>
                    <div class="col-sm-9 col-xs-9 reply-main">
                        <textarea class="form-control" rows="1" id="comment"></textarea>
                    </div>

                    <div id='send' class="col-sm-1 col-xs-1 reply-send">
                        <i class="fa fa-send fa-2x " aria-hidden="true "></i>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js "></script>
    <script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-analytics.js "></script>
    <script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-firestore.js "></script>
    <script src="http://code.jquery.com/jquery-1.10.2.min.js "></script>

    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js "></script>
    <script src="{% static 'chatpannel/js/chat.js' %}"></script>
    <script>
        if (sessionStorage.getItem('user') == null) {
            location.href = '/googleauth/1';
        }
        var check = false;
        (async() => {
            var firestore = firebase.firestore();
            var user = firestore.doc(sessionStorage.getItem('user'));
            var docdata = await user.get();
            if (docdata.data()['Doc Id'] == null)
                location.href = '/googleauth/1';
            check = true;
            if (check)
                main(`${docdata.data()['Doc Id']}`);

        })();

        function updateScroll() {
            var element = document.getElementById("chatmess");
            element.scrollTop = element.scrollHeight;
        }

        // console.log('cds');

        updateScroll();

        // 	$(function(){
        //     $(".heading-compose ").click(function() {
        //       $(".side-two ").css({
        //         "left ": "0 "
        //       });
        //     });

        //     $(".newMessage-back ").click(function() {
        //       $(".side-two ").css({
        //         "left ": "-100% "
        //       });
        //     });
        // })
    </script>
</body>

</html>

app/templates/coomingsoon.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Comming Soon</title>
  </head>
  <style>
      .mar{
         margin-top: 10%;
         margin-left: 35%;
      }
  </style>
  <body>
    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Coming Soon</h1>
    <p class="lead">Under Construction</p>
  </div>
</div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/enter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.5">
    <title>Sapphire Meet</title>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<style>
   @import url(https://fonts.googleapis.com/css?family=Exo:100,200,400);
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);

body{
	margin: 0;
	padding: 0;
	background: #fff;

	color: #fff;
	font-family: Arial;
	font-size: 12px;
}

.body{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: 100%;
	background-image: url(https://c0.wallpaperflare.com/preview/389/615/630/business-businessman-communication-concept.jpg);
	background-size: cover;
	-webkit-filter: blur(1px);
	z-index: 0;
}

.grad{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
	z-index: 1;
	opacity: 0.7;
}

.header{
	position: absolute;
	top: calc(50% - 35px);
	left: calc(50% - 255px);
	width:20%;


}

.header div{
	float: left;
	color: blue;
	font-family: 'Exo', sans-serif;
	font-size: 35px;
	font-weight: 200;
}

.header div span{
	color: #5379fa !important;
}

.login{
	position: absolute;
	top: 30%;
	left: 40% ;
	height: 150px;
	width: 350px;
	padding: 10px;
	z-index: 2;
}

.login input[type=text]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
}

.login input[type=text]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
	margin-top: 10px;
}
.join{
    font-size:60px;
    font-weight: 700;
}
.login input[type=submit]{
	width: 260px;
	height: 35px;
	background: #fff;
	border: 1px solid #fff;
	cursor: pointer;
	border-radius: 2px;
	color: #a18d6c;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 6px;
	margin-top: 10px;
}

.login input[type=submit]:hover{
	opacity: 0.8;
}

.login input[type=submit]:active{
	opacity: 0.6;
}

.login input[type=text]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=text]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=submit]:focus{
	outline: none;
}

::-webkit-input-placeholder{
   color: rgba(255,255,255,0.6);
}

::-moz-input-placeholder{
   color: rgba(255,255,255,0.6);
}

</style>
<body>

    <form class="needs-validation mar" action="{%url 'sapphiremeetapp:channel'%}" novalidate method="post">  {% csrf_token %}
      <div class="body"></div>
		<div class="grad"></div>

		<br>
		<div class="login">
		    <div class ='join'>      Join   Meeting </div>
			<br>
				<input type="text" placeholder="YOUR NAME" name="name"><br>

				<input type="text" placeholder="Room ID" name="roomid"><br>


				<input type="submit" value="ENTER ROOM">
		</div>

      </form>

</body>

</html>